## Импорт библиотек

In [3]:
import pandas as pd

# Путь к папке с данными
DATA_PATH = "../../data"

## Описание данных

У нас есть таблицы с данными о продажах товаров некоторого маркетплейса.

### Таблица с событиями `events.csv`

**Описание признаков:**

- `timestamp` — время события
- `visitorid` — идентификатор пользователя
- `event` — тип события
    - `view` - просмотр
    - `addtocart` - добавление в корзину
    - `transaction` - транзакция (покупка)
- `itemid` — идентификатор объекта
- `transactionid` — идентификатор транзакции, если она проходила

### Таблица с деревом категорий `category_tree.csv`

**Описание признаков:**

- `category_id` — идентификатор категорий
- `parent_id` — идентификатор родительской категории

### Таблицы со свойствами товаров `item_properties_part1.csv`, `item_properties_part2.csv`

**Описание признаков:**

- `timestamp` — момент записи значения свойства
- `item_id` — идентификатор объекта
- `property` — свойство, кажется, они все, кроме категории, захешированы
- `value` — значение свойства

Загрузим эти таблицы и посмотрим на их первые строки.

In [4]:
# Данные о событиях
events_data = pd.read_csv(f"{DATA_PATH}/events.csv")

# Данные о структуре каталога
category_data = pd.read_csv(f"{DATA_PATH}/category_tree.csv")

# Данные о товарах
items_data = pd.concat([
    pd.read_csv(f"{DATA_PATH}/item_properties_part1.csv"),
    pd.read_csv(f"{DATA_PATH}/item_properties_part2.csv")
])

In [5]:
events_data.head()

       timestamp  visitorid event  itemid  transactionid
0  1433221332117     257597  view  355908            NaN
1  1433224214164     992329  view  248676            NaN
2  1433221999827     111016  view  318965            NaN
3  1433221955914     483717  view  253185            NaN
4  1433221337106     951259  view  367447            NaN

In [6]:
category_data.head()

   categoryid  parentid
0        1016     213.0
1         809     169.0
2         570       9.0
3        1691     885.0
4         536    1691.0

In [7]:
items_data.head()

       timestamp  itemid    property                            value
0  1435460400000  460429  categoryid                             1338
1  1441508400000  206783         888          1116713 960601 n277.200
2  1439089200000  395014         400  n552.000 639502 n720.000 424566
3  1431226800000   59481         790                       n15360.000
4  1431831600000  156781         917                           828513

## Исследование данных

Вынесено в файл [02_eda.ipynb](./02_eda.ipynb)

## Создание признаков

Вынесено в файл [03_feature_inginiring.ipynb](./03_feature_inginiring.ipynb)