# Создание признаков

## Импорт библиотек

In [ ]:
import pandas as pd

from rec_sys.utils.prepare_data import (
    convert_timespamp_to_datetime,
    add_datetime_features,
)

pd.set_option('display.max_colwidth', None)

# Путь к папке с данными
DATA_PATH = "../../data"

## Загрузка данных

Описание исходных данных находится в основном файле [01_main.ipynb](./01_main.ipynb).

In [2]:
# Данные о событиях
events_data = pd.read_csv(f"{DATA_PATH}/events.csv")

# Данные о структуре каталога
category_data = pd.read_csv(f"{DATA_PATH}/category_tree.csv")

# Данные о товарах
items_data = pd.concat([
    pd.read_csv(f"{DATA_PATH}/item_properties_part1.csv"),
    pd.read_csv(f"{DATA_PATH}/item_properties_part2.csv")
])

In [ ]:
# Добавим признак с временем события в формате YYYY-MM-DD HH:MM:SS
events_data = convert_timespamp_to_datetime(events_data)
items_data = convert_timespamp_to_datetime(items_data)

Посмотрим на первые строки таблиц.

In [4]:
events_data.head()

   visitorid      event  itemid  transactionid          event_datetime
0     693516  addtocart  297662            NaN 2015-05-03 03:00:04.384
1     829044       view   60987            NaN 2015-05-03 03:00:11.289
2     652699       view  252860            NaN 2015-05-03 03:00:13.048
3    1125936       view   33661            NaN 2015-05-03 03:00:24.154
4     693516       view  297662            NaN 2015-05-03 03:00:26.228

In [5]:
category_data.head()

   categoryid  parentid
0        1016     213.0
1         809     169.0
2         570       9.0
3        1691     885.0
4         536    1691.0

In [6]:
items_data.head()

   itemid   property       value      event_datetime
0  317951        790  n32880.000 2015-05-10 03:00:00
1  422842        480     1133979 2015-05-10 03:00:00
2  310185        776      103591 2015-05-10 03:00:00
3  110973        112      679677 2015-05-10 03:00:00
4  179597  available           0 2015-05-10 03:00:00

In [9]:
events_data = add_datetime_features(events_data)

events_data.head()

,visitorid,event,itemid,transactionid,event_datetime,day_of_week,year,month,day,hour,minute
0,693516,addtocart,297662,NaN,2015-05-03 03:00:04.384,6,2015,5,3,3,0
1,829044,view,60987,NaN,2015-05-03 03:00:11.289,6,2015,5,3,3,0
2,652699,view,252860,NaN,2015-05-03 03:00:13.048,6,2015,5,3,3,0
3,1125936,view,33661,NaN,2015-05-03 03:00:24.154,6,2015,5,3,3,0
4,693516,view,297662,NaN,2015-05-03 03:00:26.228,6,2015,5,3,3,0